import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Smartjects",
  description: "Terms of Service for Smartjects platform",
};

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">Terms of Service</h1>
      <p className="text-gray-600 mb-8">Effective Date: July 01, 2025</p>

      <div className="prose prose-lg max-w-none">
        <p>
          Welcome to Smartjects.com ("Smartjects," "we," "our," or "us"). These
          Terms of Service ("Terms") govern your use of our website, services,
          and platform located at https://www.smartjects.com (the "Platform").
        </p>

        <p>
          By accessing or using Smartjects, you agree to be bound by these Terms.
          If you do not agree, do not use the Platform.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Platform Overview</h2>
        <p>
          Smartjects.com enables users to explore, react to, and propose
          implementations for structured AI-based innovation projects
          ("smartjects"), based on research and industry use cases. It connects
          companies, researchers, and providers through a collaborative and
          contract-based environment.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Eligibility</h2>
        <p>
          You must be at least 18 years old and capable of entering into a
          binding legal agreement. Use of the Platform is for business,
          professional, or research purposes only.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Account Registration</h2>
        <p>
          To access certain features, you must create an account. You agree to:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Provide accurate, current information;</li>
          <li>Keep your login credentials secure;</li>
          <li>Take responsibility for activity under your account.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these Terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. User Responsibilities</h2>
        <p>As a user, you agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the Platform for illegal, unethical, or misleading purposes;</li>
          <li>
            Copy, scrape, reverse-engineer, or interfere with the functionality
            of the Platform;
          </li>
          <li>Post unauthorized or infringing content;</li>
          <li>Misrepresent your affiliation, expertise, or abilities.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          5. User Content and Intellectual Property
        </h2>
        <p>
          You retain ownership of the content you submit (e.g., proposals,
          comments, documentation). By posting or uploading content, you grant us
          a non-exclusive, royalty-free license to use it for operating and
          promoting the Platform.
        </p>
        <p>
          Smartjects retains ownership of its technology, branding, and all
          content generated by the system or stored in connection with the
          service, excluding user submissions.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          6. Voting, Proposals, and Smartject Contracts
        </h2>
        <p>The Platform enables the following interactive features:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Reactions: "I believe," "I need," and "I provide" votes;</li>
          <li>Smartject Proposals: Submissions with detailed implementation plans;</li>
          <li>
            Smartject Contracts: When "I need" and "I provide" users mutually
            agree, a software-based contract is created.
          </li>
        </ul>
        <p>
          Smartjects does not act as a party to the contract. We are not liable
          for performance, payments, or outcomes of any agreement made through
          the Platform.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Confidentiality and Privacy</h2>
        <p>
          Some proposals or matches may involve private data. We strive to
          preserve confidentiality between users, especially for "I need" / "I
          provide" roles, until matched. Please refer to our{" "}
          <a href="/privacy-policy" className="text-[#FF7100]">
            Privacy Policy
          </a>{" "}
          for more details.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Termination</h2>
        <p>
          You may delete your account at any time. We may suspend or terminate
          access for violations of these Terms, harmful behavior, or legal
          obligations, with or without notice.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Disclaimers</h2>
        <p>
          The Platform is provided "as is" without warranty of any kind. We do
          not guarantee project success, accuracy of user-submitted content, or
          uninterrupted availability.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Limitation of Liability</h2>
        <p>To the fullest extent permitted by law, Smartjects is not liable for:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Any indirect or consequential losses;</li>
          <li>
            Damages resulting from user actions, third-party interactions, or
            data loss;
          </li>
          <li>Project, proposal, or contract-related outcomes or disputes.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">11. Modifications</h2>
        <p>
          We may modify these Terms from time to time. We will notify users of
          significant changes. Continued use of the Platform constitutes
          acceptance of revised Terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">12. Governing Law and Jurisdiction</h2>
        <p>
          These Terms are governed by the laws of Luxembourg. Disputes shall be
          resolved in the competent courts of Luxembourg.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">13. Contact Us</h2>
        <p>If you have questions or concerns about these Terms, please contact:</p>
        <p>
          Email:{" "}
          <a href="mailto:team@smartjects.com" className="text-[#FF7100]">
            team@smartjects.com
          </a>
        </p>
        <p>Address: 2, Rue Pierre-Joseph Redouté, 2435 Luxembourg</p>
      </div>
    </div>
  );
}
